# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         C-Scan-Constants
version:      1.011
version_from: lib/C/Scan/Constants.pm
installdirs:  site
requires:
    File::Copy:                    0
    File::Path:                    0
    File::Spec:                    0
    File::Temp:                    0
    List::MoreUtils:               0
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
